// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnoltbgfatheyhmsltpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub2x0YmdmYXRoZXlobXNsdHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzc0NjksImV4cCI6MjA3Mjc1MzQ2OX0.TQ_xa42b9KtUWWaqtTTtNwTKn4t-3tppid6D2nIB1wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});